# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('author', models.CharField(default='', max_length=300)),
                ('genre', models.CharField(choices=[('No Genre', 'No Genre'), ('Comedy', 'Comedy'), ('Crime/Thriller', 'Crime/Thriller'), ('Factual', 'Factual'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Science Fiction/Fantasy', 'Science Fiction/Fantasy'), ('Crime/Thriller', 'Crime/Thriller')], default='No Genre', max_length=30)),
                ('description', models.TextField()),
                ('excerpt', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('file', models.FileField(upload_to='')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
