# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('No Genre', 'No Genre'), ('Comedy', 'Comedy'), ('Crime/Thriller', 'Crime/Thriller'), ('Factual', 'Factual'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Science Fiction/Fantasy', 'Science Fiction/Fantasy'), ('Crime/Thriller', 'Crime/Thriller')], default='No Genre', max_length=30),
        ),
    ]
