# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20181201_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='xyz',
        ),
    ]
