# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_xyz'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default='a@a.co.uk', max_length=254),
        ),
    ]
