# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
    ]
