# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
