# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20181204_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
