# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20181204_0510'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.RenameModel(
            old_name='Details',
            new_name='Order',
        ),
        migrations.RemoveField(
            model_name='orderedbook',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderedbook',
            name='orderedbook',
        ),
        migrations.DeleteModel(
            name='OrderedBook',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
    ]
